In [25]:
import tensorflow.keras as keras
import numpy as np
import pandas as pd
import sklearn
from keras import models
from keras import layers

In [26]:
train = pd.read_csv(r"C:\Users\Aryan Raj\Desktop\Kaggle\Digit_Recognizer\train.csv")
train.head()

,label,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,1,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,4,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [27]:
test = pd.read_csv(r"C:\Users\Aryan Raj\Desktop\Kaggle\Digit_Recognizer\test.csv")
test.head()

,pixel0,pixel1,pixel2,pixel3,pixel4,pixel5,pixel6,pixel7,pixel8,pixel9,...,pixel774,pixel775,pixel776,pixel777,pixel778,pixel779,pixel780,pixel781,pixel782,pixel783
0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [28]:
train_data = train.copy()
train_labels = train_data['label'].astype('float32')
train_data = train_data.drop(['label'], axis=1).astype('int32')
test_data = test.copy()

In [29]:
from keras.utils.np_utils import to_categorical
train_labels = to_categorical(train_labels)

In [30]:
train_data.shape, train_labels.shape, test_data.shape

((42000, 784), (42000, 10), (28000, 784))

In [31]:
train_data = train_data.values.reshape(-1, 28, 28, 1)
train_data = train_data/255.0
test_data = test_data.values.reshape(-1, 28, 28, 1)
test_data = test_data/255.0
train_data.shape, test_data.shape

((42000, 28, 28, 1), (28000, 28, 28, 1))

In [32]:
model = models.Sequential()
model.add(layers.Conv2D(32, (3, 3), activation='relu', input_shape=(28, 28, 1)))
model.add(layers.Conv2D(32, (3, 3), activation="relu"))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))
model.add(layers.Conv2D(64, (3, 3), padding="same", activation="relu"))
model.add(layers.Conv2D(64, (3, 3), padding="same", activation="relu"))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))
model.add(layers.Conv2D(64, (3, 3), padding="same", activation="relu"))
model.add(layers.Conv2D(64, (3, 3), padding="same", activation="relu"))
model.add(layers.MaxPooling2D(pool_size=(2, 2)))
model.add(layers.Dropout(0.25))
model.add(layers.Flatten())
model.add(layers.Dense(64, activation='relu'))
model.add(layers.Dense(10, activation='softmax'))
model.summary()

Model: "sequential_7"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
conv2d_28 (Conv2D)           (None, 26, 26, 32)        320
_________________________________________________________________
conv2d_29 (Conv2D)           (None, 24, 24, 32)        9248
_________________________________________________________________
max_pooling2d_11 (MaxPooling (None, 12, 12, 32)        0
_________________________________________________________________
conv2d_30 (Conv2D)           (None, 12, 12, 64)        18496
_________________________________________________________________
conv2d_31 (Conv2D)           (None, 12, 12, 64)        36928
_________________________________________________________________
max_pooling2d_12 (MaxPooling (None, 6, 6, 64)          0
_________________________________________________________________
conv2d_32 (Conv2D)           (None, 6, 6, 64)          36928
_________________________________________________________________
conv2d_33 (Conv2D)           (None, 6, 6, 64)          36928
_________________________________________________________________
max_pooling2d_13 (MaxPooling (None, 3, 3, 64)          0
_________________________________________________________________
dropout_2 (Dropout)          (None, 3, 3, 64)          0
_________________________________________________________________
flatten_2 (Flatten)          (None, 576)               0
_________________________________________________________________
dense_3 (Dense)              (None, 64)                36928
_________________________________________________________________
dense_4 (Dense)              (None, 10)                650
=================================================================
Total params: 176,426
Trainable params: 176,426
Non-trainable params: 0
_________________________________________________________________

In [33]:
model.compile(optimizer='Adam', loss='categorical_crossentropy', metrics=['accuracy'])

In [34]:
model.fit(x=train_data, y=train_labels, validation_split=0.1, batch_size=50, epochs=10, verbose=2)

Train on 37800 samples, validate on 4200 samples
Epoch 1/5
 - 61s - loss: 0.2122 - accuracy: 0.9313 - val_loss: 0.0513 - val_accuracy: 0.9831
Epoch 2/5
 - 59s - loss: 0.0584 - accuracy: 0.9812 - val_loss: 0.0339 - val_accuracy: 0.9883
Epoch 3/5
 - 59s - loss: 0.0429 - accuracy: 0.9867 - val_loss: 0.0316 - val_accuracy: 0.9879
Epoch 4/5
 - 59s - loss: 0.0343 - accuracy: 0.9888 - val_loss: 0.0346 - val_accuracy: 0.9893
Epoch 5/5
 - 60s - loss: 0.0300 - accuracy: 0.9904 - val_loss: 0.0283 - val_accuracy: 0.9900

In [35]:
results = model.predict(test_data)
results = np.argmax(results, axis=1)
results = pd.Series(results, name="Label")

In [36]:
results.shape

(28000,)

In [37]:
print(results)

0        2
1        0
2        9
3        9
4        3
        ..
27995    9
27996    7
27997    3
27998    9
27999    2
Name: Label, Length: 28000, dtype: int64

In [ ]:
submission = pd.concat([pd.Series(range(1, 28001), name = "ImageId"), results], axis=1)
submission.to_csv("submission.csv", index=False)